name: 'Terraform Azure RG Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2

    - name: 'Terraform Init'
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID:       ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.ARM_TENANT_ID }}
      run: terraform init

    - name: 'Terraform Plan'
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID:       ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID:       ${{ secrets.ARM_TENANT_ID }}
      run: terraform plan

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main'
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID:       ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID:       ${{ secrets.ARM_TENANT_ID }}
      run: terraform apply -auto-approve
