name: 'Terraform Azure RG Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2

    - name: 'Terraform Init'
      run: terraform init
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
      

    - name: 'Terraform Plan'
      run: terraform plan
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
      
      
