name: 'Terraform Destroy Azure RG'

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2

    - name: 'Terraform Init'
      run: terraform init
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}

    - name: 'Terraform Destroy'
      run: terraform destroy -auto-approve
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
